all:
	cc -O -Wall -W -pedantic -ansi -std=c99 -o ex1 ex1.c
	cc -O -Wall -W -pedantic -ansi -std=c99 -o ex2 ex2.c
	cc -O -Wall -W -pedantic -ansi -std=c99 -o ex4 ex4.c
	cc -O -Wall -W -pedantic -ansi -std=c99 -o ex5 ex5.c
	cc -O -Wall -W -pedantic -ansi -std=c99 -o ex6 ex6.c

clean:
	rm -f ex1 ex2 ex3 ex4 ex5 ex6
