all:
	cc -O -Wall -W -pedantic -ansi -std=c99 -o pun pun.c
	cc -O -Wall -W -pedantic -ansi -std=c99 -o dweight dweight.c
	cc -O -Wall -W -pedantic -ansi -std=c99 -o dweight2 dweight2.c
	cc -O -Wall -W -pedantic -ansi -std=c99 -o celcius celcius.c

clean:
	rm -f pun dweight2 dweight celcius
