all:
	cc -O -Wall -W -pedantic -ansi -std=c99 -o hw hw.c
	cc -O -Wall -W -pedantic -ansi -std=c99 -o dweight dweight.c
	cc -O  -std=c99 -o ex4 ex4.c
	cc -O -Wall -W -pedantic -ansi -std=c99 -o proj1 proj1.c
	cc -O -Wall -W -pedantic -ansi -std=c99 -o proj2 proj2.c
	cc -O -Wall -W -pedantic -ansi -std=c99 -o proj3 proj3.c
	cc -O -Wall -W -pedantic -ansi -std=c99 -o proj4 proj4.c
	cc -O -Wall -W -pedantic -ansi -std=c99 -o proj5 proj5.c
	cc -O -Wall -W -pedantic -ansi -std=c99 -o proj6 proj6.c
	cc -O -Wall -W -pedantic -ansi -std=c99 -o proj7 proj7.c

clean:
	rm -f hw dweight ex4 proj1 proj2 proj3 proj4 proj5 proj6 proj7
