all:
	cc -O -Wall -W -pedantic -ansi -std=c99 -o ex1 ex1.c
	cc -O -Wall -W -pedantic -ansi -std=c99 -o ex2 ex2.c
	cc -O -Wall -W -pedantic -ansi -std=c99 -o ex3 ex3.c
	cc -O -Wall -W -pedantic -ansi -std=c99 -o ex8 ex8.c

clean:
	rm -f ex1 ex2 ex3 ex4 ex5 ex6 ex8
